package models

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

// Status represents the lifecycle state of an order.
type Status string

const (
	StatusReceived  Status = "Received"
	StatusPreparing Status = "Preparing"
	StatusComplete  Status = "Complete"
	StatusCancelled Status = "Cancelled"
)

// IsValid returns true if s is one of the four recognised statuses.
func (s Status) IsValid() bool {
	switch s {
	case StatusReceived, StatusPreparing, StatusComplete, StatusCancelled:
		return true
	}
	return false
}

// allowedTransitions maps each status to the set of statuses it may transition into.
// Any transition not listed here is rejected by the service layer.
var allowedTransitions = map[Status][]Status{
	StatusReceived:  {StatusPreparing, StatusCancelled},
	StatusPreparing: {StatusComplete, StatusCancelled},
	StatusComplete:  {},
	StatusCancelled: {},
}

// CanTransitionTo returns true if transitioning from the receiver to next is allowed.
func (s Status) CanTransitionTo(next Status) bool {
	allowed, ok := allowedTransitions[s]
	if !ok {
		return false
	}
	for _, a := range allowed {
		if a == next {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Item — a single line-item within an order.
// ---------------------------------------------------------------------------

// Item represents one menu item in an order.
type Item struct {
	ItemID string `json:"itemId"`
	Qty    int    `json:"qty"`
}

// Items is a slice of Item that implements the GORM / database/sql value/scanner
// interfaces so it can be stored as JSONB in PostgreSQL.
type Items []Item

// Value implements driver.Valuer for database serialisation.
func (it Items) Value() (driver.Value, error) {
	if it == nil {
		return "[]", nil
	}
	b, err := json.Marshal(it)
	if err != nil {
		return nil, fmt.Errorf("items marshal: %w", err)
	}
	return string(b), nil
}

// Scan implements sql.Scanner for database deserialisation.
func (it *Items) Scan(value interface{}) error {
	if value == nil {
		*it = Items{}
		return nil
	}
	var b []byte
	switch v := value.(type) {
	case []byte:
		b = v
	case string:
		b = []byte(v)
	default:
		return fmt.Errorf("items scan: unsupported type %T", value)
	}
	return json.Unmarshal(b, it)
}

// ---------------------------------------------------------------------------
// Order — the primary domain model.
// ---------------------------------------------------------------------------

// Order is the database model and the primary domain entity.
// It is stored in the "orders" table.
type Order struct {
	// OrderID is a UUID generated by the backend on order creation.
	OrderID string `gorm:"column:order_id;primaryKey" json:"orderId"`

	CustomerID   string `gorm:"column:customer_id;not null" json:"customerId"`
	RestaurantID string `gorm:"column:restaurant_id;not null" json:"restaurantId"`

	// Status is stored as TEXT in PostgreSQL but enforced as an enum in Go.
	Status Status `gorm:"column:status;not null;default:'Received'" json:"status"`

	// Items is stored as JSONB; custom Value/Scan handles serialisation.
	Items Items `gorm:"column:items;type:jsonb;not null;default:'[]'" json:"items"`

	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;autoUpdateTime" json:"updatedAt"`
}

// TableName overrides the GORM default table name.
func (Order) TableName() string {
	return "orders"
}
